# This file has been generated by node2nix 1.8.0. Do not edit!

{ source, nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [ ] }:

let
  sources = {
    "ua-parser-js-0.7.21" = {
      name = "ua-parser-js";
      packageName = "ua-parser-js";
      version = "0.7.21";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.21.tgz";
        sha512 =
          "+O8/qh/Qj8CgC6eYBVBykMrNtp5Gebn4dlGD/kKXVkJNDwyrAwSIqwz8CDf+tsAIWVycKcku6gIXJ0qwx/ZXaQ==";
      };
    };
    "unique-names-generator-4.3.0" = {
      name = "unique-names-generator";
      packageName = "unique-names-generator";
      version = "4.3.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/unique-names-generator/-/unique-names-generator-4.3.0.tgz";
        sha512 =
          "uNX6jVFjBXfZtsc7B8jVPJ3QdfCF/Sjde4gxsy3rNQmHuWGFarnU7IFGdxZKJ4h4uRjANQc6rG7GiGolRW9fgA==";
      };
    };
    "ws-7.3.1" = {
      name = "ws";
      packageName = "ws";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.3.1.tgz";
        sha512 =
          "D3RuNkynyHmEJIpD2qrgVkc9DQ23OrN/moAwZX4L8DfvszsJxpjQuUq3LMx6HoYji9fbIOBY18XWBsAux1ZZUA==";
      };
    };
  };
  args = {
    name = "snapdrop";
    packageName = "snapdrop";
    version = "1.0.0";
    src = "${source}/server";

    dependencies = [
      sources."ua-parser-js-0.7.21"
      sources."unique-names-generator-4.3.0"
      sources."ws-7.3.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in {
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
